### ISSUE TITLE
bpe_simple_vocab_16e6.txt.gz   is not a gzip file

### ISSUE THREAD

**Issue by CDLCHOI** [blackgold3/SemanticBoost#2]
I simply run the inference code, **python inference.py --prompt "A person walks forward and sits down on the chair." --length "120" --mode ncamd --size 1024 --render "3dslow" -f -e**, and encounter the problem
Traceback (most recent call last):
  File "/root/project/SemanticBoost-main/inference.py", line 2, in <module>
    from mdm.visual_api import Visualize  
  File "/root/project/SemanticBoost-main/mdm/visual_api.py", line 17, in <module>
    from mdm.sample import Predictor as mdm_predictor
  File "/root/project/SemanticBoost-main/mdm/sample.py", line 5, in <module>
    from mdm.model_util import create_model_and_diffusion, load_model_wo_clip, create_trt_model
  File "/root/project/SemanticBoost-main/mdm/model_util.py", line 1, in <module>
    from mdm.model.mdm import MDM
  File "/root/project/SemanticBoost-main/mdm/model/mdm.py", line 5, in <module>
    from mdm.model import clip
  File "/root/project/SemanticBoost-main/mdm/model/clip/__init__.py", line 1, in <module>
    from .clip import *
  File "/root/project/SemanticBoost-main/mdm/model/clip/clip.py", line 28, in <module>
    _tokenizer = _Tokenizer()
  File "/root/project/SemanticBoost-main/mdm/model/clip/simple_tokenizer.py", line 66, in __init__
    merges = gzip.open(bpe_path).read().decode("utf-8").split('\n')
  File "/opt/conda/envs/boost/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/opt/conda/envs/boost/lib/python3.9/gzip.py", line 487, in read
    if not self._read_gzip_header():
  File "/opt/conda/envs/boost/lib/python3.9/gzip.py", line 435, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b've')

Is it a problem file?    mdm/model/clip/bpe_simple_vocab_16e6.txt.gz

**Comment by CDLCHOI** [comment]
I simply remove the suffix .gz and open the .txt file, the content is:

version https://git-lfs.github.com/spec/v1
oid sha256:924691ac288e54409236115652ad4aa250f48203de50a9e4722a6ecd48d6804a
size 1356917

**Comment by blackgold3** [comment]
This repo is uploaded with git-lfs. Maybe you can try
`
git lfs install &
git clone https://github.com/blackgold3/SemanticBoost.git
`
If it does not work, this file is from 

> https://github.com/openai/CLIP/tree/main/clip

Please replace it with the source file.

**Comment by CDLCHOI** [comment]
Thanks. git lfs does not work ， but I get it from the source
