### ISSUE TITLE
GLError

### ISSUE THREAD

**Issue by Asianfleet** [blackgold3/SemanticBoost#4]
the command I run:

python inference.py --prompt "A person walks forward and sits down on the chair." --length "120" --mode ncamd --size 1024 --render "3dslow" -f -e

the output:

Loading midfile/ncamd_clip.engine for TensorRT inference...
Loading midfile/ncamd_decoder.engine for TensorRT inference...
.........................
Visualize Mode ->  smpl
libEGL warning: MESA-LOADER: failed to open vgem: /usr/lib/dri/vgem_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

libEGL warning: NEEDS EXTENSION: falling back to kms_swrast
libEGL warning: MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

Traceback (most recent call last):
  File "/home/legion4080/MYXY/AI_pkgs/SemanticBoost/inference.py", line 120, in <module>
    out_path = interface(opt.prompt, mode=opt.mode, render_mode=opt.render, out_size=opt.size, tada_role=opt.role, length=opt.length, follow=opt.follow, export=opt.export)
  File "/home/legion4080/MYXY/AI_pkgs/SemanticBoost/inference.py", line 76, in interface
    pics = visual.pyrender_process(meshes, out_size, out_size, follow=follow)
  File "/home/legion4080/MYXY/AI_pkgs/SemanticBoost/mdm/visual_api.py", line 145, in pyrender_process
    r = pyrender.OffscreenRenderer(weight, height)
  File "/home/legion4080/anaconda3/envs/Sboost/lib/python3.9/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/legion4080/anaconda3/envs/Sboost/lib/python3.9/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/legion4080/anaconda3/envs/Sboost/lib/python3.9/site-packages/pyrender/platforms/egl.py", line 177, in init_context
    assert eglInitialize(self._egl_display, major, minor)
  File "/home/legion4080/anaconda3/envs/Sboost/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/home/legion4080/anaconda3/envs/Sboost/lib/python3.9/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
        err = 12289,
        baseOperation = eglInitialize,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7fba193d44c0>,
                c_long(0),
                c_long(0),
        ),
        result = 0
)

system:WSL2 Ubuntu 22.04
GPU:4080Laptop

**Comment by blackgold3** [comment]
The error is caused by the missing dependencies of Pyrender.  Maybe you can try `sudo apt-get install freeglut3-dev`. I'm not sure if windows WSL will influence the GLU package. If it does not wok,  please open the exported fbx file with blender application to visualization.  (-e will export fbx file)
